# Microservices Configuration
services:
  replicator:
    name: "Enhanced Replicator Service"
    url: "http://localhost:8001"
    port: 8001
    health_endpoint: "/health"
    capabilities:
      - telegram_replication
      - discord_sending
      - watermark_processing
      - file_processing
    
  watermark:
    name: "Watermark Service"
    url: "http://localhost:8081"
    port: 8081
    health_endpoint: "/health"
    capabilities:
      - image_watermark
      - text_overlay
      - batch_processing
    
  discovery:
    name: "Discovery Service"
    url: "http://localhost:8002"
    port: 8002
    health_endpoint: "/health"
    capabilities:
      - chat_discovery
      - auto_scan
      - telegram_integration

# Configuration for each service
service_configs:
  replicator:
    max_workers: 10
    message_queue_size: 1000
    retry_attempts: 3
    timeout: 30
    
  watermark:
    max_image_size: 10485760  # 10MB
    supported_formats: ["png", "jpg", "jpeg", "gif"]
    watermark_opacity: 0.3
    
  discovery:
    scan_interval: 300  # 5 minutes
    max_chats: 1000
    auto_scan: true
